### ISSUE TITLE
JSON::ParseError when nginx returns 404

### ISSUE THREAD

**Issue by bschaeffer** [transloadit/ruby-sdk#24]
Sometimes the API returns a basic HTML 404 that the SDK tries to parse anyway, and I'm getting `JSON::ParseError` exception notifications from the following response:

```html
<html>
  <head>
    <title>404 Not Found</title>
  </head>
    <body bgcolor="white">
      <center>
        <h1>404 Not Found</h1>
      </center>
      <hr>
      <center>nginx/1.7.1</center>
    </body>
</html>
```

Totally understand the API being unreachable every so often (this happened only twice in two minutes), but I did expect the SDK to catch the 404 response and raise it's own exception or return a response object.

**Comment by rmehner** [comment]
Closing this, as this is quite old and was actually a bug in the server side code at Transloadit which is long fixed :)
