### ISSUE TITLE
Synchronous Processing does not complete for large files

### ISSUE THREAD

**Issue by namor** [transloadit/ruby-sdk#25]
As per documentation, to do synchronous processing 

```ruby
# loop until processing is finished
until response.finished?
  sleep 1; response.reload! # you'll want to implement a timeout in your production app
end
```
I use this code but it locks up the ruby thread indefinitely (even though Assembly has completed) only when i upload large files ~ 3GB 
 < 1 gb files works fine which makes this a very odd problem

Is there an internal timeout which is not caught?

**Comment by rmehner** [comment]
Closing this, nearly a year ago without any new information :)

Feel free to reopen this if you have more information. Have a great day!
