### ISSUE TITLE
Detect duplicate step names

### ISSUE THREAD

**Issue by janko-m** [transloadit/ruby-sdk#27]
Awesome library! One improvement came to mind. Since we're building steps as an array of objects, it would be nice for the library to detect if the user accidentally named two different steps with the same name, and raise an error. I just think that the way assemblies are built, this mistake can happen easily.

The current behaviour is probably that the latter step will silently override the previous, and I was just thinking that it would be great to explicitly let the user know that they made a mistake.

**Comment by kvz** [comment]
Sounds like a nice improvement! I suppose you ran into this while hammering out the [shrine integration](https://github.com/janko-m/shrine-transloadit)?

**Comment by janko-m** [comment]
I haven't encountered this error in actual, but when writing examples I realized that it's easy to accidentally give two steps with the same robot the same name. In shrine-transloadit I already added the [check for unique step names](https://github.com/janko-m/shrine-transloadit/blob/d8b48594be3b1ac83402e738b4317a071c868b8f/lib/shrine/plugins/transloadit.rb#L259-L261).
