### ISSUE TITLE
Loosen dependency on mime-types gem to make compatible with Rails 5

### ISSUE THREAD

**Issue by townhouse** [transloadit/ruby-sdk#29]
Thanks for your work on this gem :)

ruby-sdk has dependency on 'mime-types', '~> 2.99'
Rails 5 depends on mime-types (3.1)

Can you loosen the dependency so ruby-sdk can be used in a Rails 5 app?

**Comment by rmehner** [comment]
I'm waiting for #28 to hit master and will cut a new version out of this then. It's fixed in master :)

Thanks for the report.

**Comment by townhouse** [comment]
Great stuff, thanks :)
