### ISSUE TITLE
Add Response#reload_until_finished!

### ISSUE THREAD

**Issue by gbuesing** [transloadit/ruby-sdk#37]
I'm creating assemblies in background jobs, and polling until they are finished so that I can save the results in the database. The README here shows a simple polling example, and notes "you'll want to implement a timeout in your production app" -- here's a helper I rolled up, with a simple max tries timeout threshold: https://gist.github.com/gbuesing/e2f0b94ae3d2f9b0c6848b82ace51201

Seems like this is a common enough pattern that it could be provided by this library, vs. everyone rolling their own. I think the api could look something like:

```ruby
response = assembly.create!
response.reload_until_finished! max_tries: 300
results = response['results'] # i.e. can work with results now, or MaxTries exception was raised
```

I don't think Ruby's Timeout is worth pursuing here, after reading http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/

**Comment by gbuesing** [comment]
Building on this, a #reload_until_completed! method could raise an exception if response.error?

**Comment by ifedapoolarewaju** [comment]
@gbuesing thank you for reaching out. This does seem like a feature worth adding. A pull-request from you too (if possible) would be much appreciated. 🙂

**Comment by rmehner** [comment]
Well either we include it as a feature, or even just an extended example in the README would also be great, so people get a starting point and can adapt things to their need.

**Comment by gbuesing** [comment]
Happy to roll up a pull request for this when I get a chance.

**Comment by rmehner** [comment]
#38 is merged and included, thanks @gbuesing :)
