### ISSUE TITLE
Git tags are missing for recent versions

### ISSUE THREAD

**Issue by janko-m** [transloadit/ruby-sdk#48]
The latest git tag on GitHub is `v1.1.0`, so the following tags are missing:

* `v1.1.1`
* `v1.1.2`
* `v1.1.3`
* `v1.1.4`
* `v1.2.0`
* `v2.0.0`
* `v2.0.1`

I would recommend using the Rake tasks provided by Bundler, which automate the process of building, releasing, tagging, and pushing:

```rb
# Rakefile
require "bundler/gem_tasks"
# ...
```
```sh
$ rake release # builds, releases, tags, and pushes the version specified in transloadit.gemspec
```

**Comment by rmehner** [comment]
Thanks for the report, as far as I can see, I forgot the `v` prefix for the tags (see here: https://github.com/transloadit/ruby-sdk/releases). 

Shall I create new tags with the `v` prefix?

Also thanks for the tip, will use that :)

**Comment by ifedapoolarewaju** [comment]
@rmehner I think we should be able to edit the releases no? I don't think I have authorization to do it, but you can probably edit each tag via the github UI and add the `v` prefix to each of them

**Comment by janko-m** [comment]
@rmehner Oh yes, you're right, I didn't see that. Usually when I want to see the latest version I look at the list of tags on the dropdown at the main page, and since the newer ones weren't on the top I assumed they were missing. Yes, so they just need to be modified somehow.

>  I think we should be able to edit the releases no? I don't think I have authorization to do it, but you can probably edit each tag via the github UI and add the v prefix to each of them

If modifying the release names modifies the corresponding git tags as well, I'm all for that 👍

**Comment by rmehner** [comment]
I think I'd prefer if we could create new tags for the same versions, that way, we don't break existing version tags that some people might rely on and for future version we use the `v` pattern again :)

**Comment by rmehner** [comment]
Pushed the missing tags :)
