### ISSUE TITLE
Assembly List fails with Signature Error

### ISSUE THREAD

**Issue by mikecx** [transloadit/ruby-sdk#49]
Using a working Transloadit Ruby-SDK setup (processes video files correctly), I cannot seem to get the assembly.list or Transloadit.bill calls to work. I have "Deny requests that do not include a signature or a wrong one?" turned off on my account for now.

```
irb(main):001:0> assembly = Transloadit.assembly
=> {:auth=>{:key=>"MY_KEY_HERE", :expires=>"2018/05/19 01:24:57+00:00"}}
```

```
irb(main):002:0> assembly.list
=> {"error"=>"INVALID_SIGNATURE", "message"=>"The given signature does not match ours."}
```

I'm pretty sure it's because the signature is not being generated/sent but that's not made clear that it needs to be sent anywhere other than the transloadit docs.

Also, there's no documentation here on how to send a signature or if it's automatic.

Edit: Inspecting the request shows that it is indeed generating a signature, unclear why it's wrong.

**Comment by ifedapoolarewaju** [comment]
Hi @mikecx I am unable to reproduce this issue. Are you passing both your api key and secret to the  `Transloadit` class  when you instantiate it?

```rb
Transloadit.new(
    :key    => 'YOUR_KEY',
    :secret => 'YOUR_SECRET'
)
```

If you are indeed passing the credentials as above, then it must mean you are passing the wrong credentials. Is it possible that you've changed your API secret on the https://transloadit.com dashboard, and forgot to update it in your project?

**Comment by mikecx** [comment]
Good call. Looks like when I moved over from my test account to my production account I updated the key but not the secret. Thanks for the help.
