### ISSUE TITLE
The signature comes after the files in the POST request payload, which causes problems

### ISSUE THREAD

**Issue by tim-kos** [transloadit/ruby-sdk#51]
In the POST payload to `/assemblies`, the signature should come right after the "params" field, and not after the files. There are various reasons:

- It will create a NO_SIGNATURE_FIELD on the Assembly in some cases, which is a race condition that I will fix on our end.
- The user should not need to wait for all of the files to upload to our server only to find out that she calculated the signature wrongly. On Transloadit's side we evaluate the signature as soon as it comes in and by that we could end the connection quickly if the signature is wrong.

Relevant code parts are:
https://github.com/transloadit/ruby-sdk/blob/master/lib/transloadit/assembly.rb#L60
https://github.com/transloadit/ruby-sdk/blob/master/lib/transloadit/request.rb#L77
https://github.com/transloadit/ruby-sdk/blob/master/lib/transloadit/request.rb#L129

I feel it's good design that the signature calculation code lives in the Request class and is added as an after thought. But I feel it might need to be moved to the assembly class and added before the files are added.

**Comment by Acconut** [comment]
Fixed in #65.
