### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by kvz** [transloadit/ruby-sdk#59]
Since Travis isn't usable for open source anymore.

When we are done, we should also update the badge at https://transloadit.com/docs/#sdks by adding this frontmatter to the ruby-sdk integration file:

```yaml
ghactions_workflow: Ruby SDK CI # assuming that becomes the github actions workflow name
```

**Comment by juliangruber** [comment]
This was already using GitHub Actions, I added an action name and created a docs PR.
