### ISSUE TITLE
Getting bill information doesn't work on Ruby 3

### ISSUE THREAD

**Issue by mingan** [transloadit/ruby-sdk#62]
What used to be a warning on Ruby 2.7 

```
gems/transloadit-2.0.1/lib/transloadit/request.rb:154: warning: URI.escape is obsolete
```

is not fully deprecated and crashes.

**Comment by Acconut** [comment]
This has been fixed in https://github.com/transloadit/ruby-sdk/pull/63. Thanks for the report!
